runtime:
  seed: 42
  device: cuda  # 'cuda' or 'cpu'

data:
  data_root: "./data/processed/Urinary Sediment Dataset"
  batch_size: 32    # (32, 64)

stage1_model_config:
  img_size: 800  # (600, 800)
  in_c: 512
  rpn_anchor_sizes : 32, 40, 64, 120, 208   # statistics-based sizes
  rpn_anchor_aspect_ratios: 0.89, 1.0, 1.15   # statistics-based ratios
  rpn_fg_iou_thresh: 0.6  # [0.5, 0.7]
  rpn_bg_iou_thresh: 0.3  # [0.2, 0.3]
  rpn_batch_size_per_image: 256  # [128, 256]
  rpn_pre_nms_top_n: 4000, 2000  # train: [2000, 6000], test: [1000, 3000]
  rpn_post_nms_top_n: 2000, 1000 # train: [2000, 4000], test: [1000, 2000]
  rpn_nms_thresh: 0.8  # [0.7, 0.9]

stage1_trainer_config:


