runtime:
  seed: 42
  device: cuda

data:
  data_root: ./data/processed/Urinary Sediment Dataset
  batch_size: 16
  img_size: 400

model:
  freeze_backbone: false
  in_c: 512
  threshold: 0.5

trainer:
  epochs: 50
  lr: 0.001
  warm_up_lr_factor: 0.01
  warmup_epochs: 5
  weight_decay: 0.05
  checkpoints_save_path: ./checkpoints/ccam/
  model_save_path: ./results/model_weights/
  continue_train: False
  checkpoint_path: ""    # ./checkpoints/ccam/checkpoint_{epoch}.pth