runtime:
  seed: 42
  device: cuda  # 'cuda' or 'cpu'

data:
  data_root: "./data/processed/Urinary Sediment Dataset"
  batch_size: 32    # (32, 64)
  img_size: 384
  num_classes: 7

prototypeChecker_config:
  in_c: 512
  embed_dim : 512
  patch_size: 3
  roi_out_size: 7
  spatial_scale: 0.125
  sampling_ratio: 2
  backbone_weights_path: "./results/model_weights/Vgg16_backbone.pth"
  patch_embed_weights_path: "./results/model_weights/patch_embed_weights.pth"
  dataset_MPs_path: "./dataset_morphological_prototypes/dataset_MPs.pth"
